//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDCharCtor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDCharCtor.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~DnDCharCtor.
        /// </summary>
        public static string App_DnDCharCtor {
            get {
                return ResourceManager.GetString("App_DnDCharCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~External libraries.
        /// </summary>
        public static string App_ExternalLibraries {
            get {
                return ResourceManager.GetString("App_ExternalLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~App info.
        /// </summary>
        public static string App_Info {
            get {
                return ResourceManager.GetString("App_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Library.
        /// </summary>
        public static string App_Library {
            get {
                return ResourceManager.GetString("App_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Transitive external libraries.
        /// </summary>
        public static string App_TransitiveExternalLibraries {
            get {
                return ResourceManager.GetString("App_TransitiveExternalLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~App version.
        /// </summary>
        public static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Discard changes.
        /// </summary>
        public static string Button_Discard {
            get {
                return ResourceManager.GetString("Button_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit character.
        /// </summary>
        public static string Button_EditCharacter {
            get {
                return ResourceManager.GetString("Button_EditCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Properties.
        /// </summary>
        public static string Button_Properties {
            get {
                return ResourceManager.GetString("Button_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Reset.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select.
        /// </summary>
        public static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Character name.
        /// </summary>
        public static string Character_Name {
            get {
                return ResourceManager.GetString("Character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Personality.
        /// </summary>
        public static string Character_Personality {
            get {
                return ResourceManager.GetString("Character_Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Attitute.
        /// </summary>
        public static string Character_Personality_Attitute {
            get {
                return ResourceManager.GetString("Character_Personality_Attitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Background.
        /// </summary>
        public static string Character_Personality_Background {
            get {
                return ResourceManager.GetString("Character_Personality_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Class.
        /// </summary>
        public static string Character_Personality_Class {
            get {
                return ResourceManager.GetString("Character_Personality_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Experience.
        /// </summary>
        public static string Character_Personality_Experience {
            get {
                return ResourceManager.GetString("Character_Personality_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Level.
        /// </summary>
        public static string Character_Personality_Level {
            get {
                return ResourceManager.GetString("Character_Personality_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Player name.
        /// </summary>
        public static string Character_Personality_PlayerName {
            get {
                return ResourceManager.GetString("Character_Personality_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Race.
        /// </summary>
        public static string Character_Personality_Race {
            get {
                return ResourceManager.GetString("Character_Personality_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Create character.
        /// </summary>
        public static string CharacterEditor_Create {
            get {
                return ResourceManager.GetString("CharacterEditor_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit character &quot;{0}&quot;.
        /// </summary>
        public static string CharacterEditor_Edit {
            get {
                return ResourceManager.GetString("CharacterEditor_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit personality.
        /// </summary>
        public static string CharacterEditor_Personality_Edit {
            get {
                return ResourceManager.GetString("CharacterEditor_Personality_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Drag or click here to upload an image.
        /// </summary>
        public static string CharacterEditor_UploadImage {
            get {
                return ResourceManager.GetString("CharacterEditor_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~You are about to delete the following character:.
        /// </summary>
        public static string Dialog_DeleteCharacterText {
            get {
                return ResourceManager.GetString("Dialog_DeleteCharacterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Delete character?.
        /// </summary>
        public static string Dialog_DeleteCharacterTitle {
            get {
                return ResourceManager.GetString("Dialog_DeleteCharacterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~There are unsaved changes. Discard changes?.
        /// </summary>
        public static string Dialog_DiscardText {
            get {
                return ResourceManager.GetString("Dialog_DiscardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Discard changes?.
        /// </summary>
        public static string Dialog_DiscardTitle {
            get {
                return ResourceManager.GetString("Dialog_DiscardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cancelled.
        /// </summary>
        public static string FileUpload_Cancelled {
            get {
                return ResourceManager.GetString("FileUpload_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Completed.
        /// </summary>
        public static string FileUpload_Completed {
            get {
                return ResourceManager.GetString("FileUpload_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Loading {0}/{1} - {2}.
        /// </summary>
        public static string FileUpload_InProgress {
            get {
                return ResourceManager.GetString("FileUpload_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Loading....
        /// </summary>
        public static string FileUpload_Loading {
            get {
                return ResourceManager.GetString("FileUpload_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Characters.
        /// </summary>
        public static string Page_Characters {
            get {
                return ResourceManager.GetString("Page_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Create character.
        /// </summary>
        public static string Page_Create {
            get {
                return ResourceManager.GetString("Page_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit character.
        /// </summary>
        public static string Page_Edit {
            get {
                return ResourceManager.GetString("Page_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Info.
        /// </summary>
        public static string Page_Info {
            get {
                return ResourceManager.GetString("Page_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Settings.
        /// </summary>
        public static string Page_Settings {
            get {
                return ResourceManager.GetString("Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~English.
        /// </summary>
        public static string Settings_Languages_English {
            get {
                return ResourceManager.GetString("Settings_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Deutsch (German).
        /// </summary>
        public static string Settings_Languages_German {
            get {
                return ResourceManager.GetString("Settings_Languages_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Language settings.
        /// </summary>
        public static string Settings_LanguageSettings {
            get {
                return ResourceManager.GetString("Settings_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select color.
        /// </summary>
        public static string Settings_SelectColor {
            get {
                return ResourceManager.GetString("Settings_SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select language.
        /// </summary>
        public static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select theme.
        /// </summary>
        public static string Settings_SelectTheme {
            get {
                return ResourceManager.GetString("Settings_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Theme settings.
        /// </summary>
        public static string Settings_ThemeSettings {
            get {
                return ResourceManager.GetString("Settings_ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cannot save since some cards and fields have validation errors.
        /// </summary>
        public static string Validation_CannotSave {
            get {
                return ResourceManager.GetString("Validation_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cannot save.
        /// </summary>
        public static string Validation_CannotSaveTitle {
            get {
                return ResourceManager.GetString("Validation_CannotSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Card &quot;{0}&quot; has the following validation errors:.
        /// </summary>
        public static string Validation_ErrorSource {
            get {
                return ResourceManager.GetString("Validation_ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Text of field &quot;{0}&quot; must contain less or equal to &quot;{1}&quot; characters.
        /// </summary>
        public static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Value of field &quot;{0}&quot; must be between &quot;{1}&quot; and &quot;{2}&quot;.
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Field &quot;{0}&quot; is required.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Value of field &quot;{0}&quot; must be an integer.
        /// </summary>
        public static string Validation_RequiredParsedInteger {
            get {
                return ResourceManager.GetString("Validation_RequiredParsedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Field is required.
        /// </summary>
        public static string Validation_Tooltip_Required {
            get {
                return ResourceManager.GetString("Validation_Tooltip_Required", resourceCulture);
            }
        }
    }
}
