//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDCharCtor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDCharCtor.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~DnDCharCtor.
        /// </summary>
        public static string App_DnDCharCtor {
            get {
                return ResourceManager.GetString("App.DnDCharCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Character name.
        /// </summary>
        public static string Character_Name {
            get {
                return ResourceManager.GetString("Character.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Personality.
        /// </summary>
        public static string Character_Personality {
            get {
                return ResourceManager.GetString("Character.Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Attitute.
        /// </summary>
        public static string Character_Personality_Attitute {
            get {
                return ResourceManager.GetString("Character.Personality.Attitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Background.
        /// </summary>
        public static string Character_Personality_Background {
            get {
                return ResourceManager.GetString("Character.Personality.Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Class.
        /// </summary>
        public static string Character_Personality_Class {
            get {
                return ResourceManager.GetString("Character.Personality.Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Experience.
        /// </summary>
        public static string Character_Personality_Experience {
            get {
                return ResourceManager.GetString("Character.Personality.Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Level.
        /// </summary>
        public static string Character_Personality_Level {
            get {
                return ResourceManager.GetString("Character.Personality.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Player name.
        /// </summary>
        public static string Character_Personality_PlayerName {
            get {
                return ResourceManager.GetString("Character.Personality.PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Race.
        /// </summary>
        public static string Character_Personality_Race {
            get {
                return ResourceManager.GetString("Character.Personality.Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Create character.
        /// </summary>
        public static string CharacterEditor_Create {
            get {
                return ResourceManager.GetString("CharacterEditor.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit character &quot;{0}&quot;.
        /// </summary>
        public static string CharacterEditor_Edit {
            get {
                return ResourceManager.GetString("CharacterEditor.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Edit personality.
        /// </summary>
        public static string CharacterEditor_Personality_Edit {
            get {
                return ResourceManager.GetString("CharacterEditor.Personality.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Home.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Settings.
        /// </summary>
        public static string Page_Settings {
            get {
                return ResourceManager.GetString("Page.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~English.
        /// </summary>
        public static string Settings_Languages_English {
            get {
                return ResourceManager.GetString("Settings.Languages.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Deutsch (German).
        /// </summary>
        public static string Settings_Languages_German {
            get {
                return ResourceManager.GetString("Settings.Languages.German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Language settings.
        /// </summary>
        public static string Settings_LanguageSettings {
            get {
                return ResourceManager.GetString("Settings.LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select color.
        /// </summary>
        public static string Settings_SelectColor {
            get {
                return ResourceManager.GetString("Settings.SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select language.
        /// </summary>
        public static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings.SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Select theme.
        /// </summary>
        public static string Settings_SelectTheme {
            get {
                return ResourceManager.GetString("Settings.SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Theme settings.
        /// </summary>
        public static string Settings_ThemeSettings {
            get {
                return ResourceManager.GetString("Settings.ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cannot save since some cards and fields have validation errors.
        /// </summary>
        public static string Validation_CannotSave {
            get {
                return ResourceManager.GetString("Validation.CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Cannot save.
        /// </summary>
        public static string Validation_CannotSaveTitle {
            get {
                return ResourceManager.GetString("Validation.CannotSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Card &quot;{0}&quot; has the following validation errors:.
        /// </summary>
        public static string Validation_ErrorSource {
            get {
                return ResourceManager.GetString("Validation.ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Field &quot;{0}&quot; is required.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation.RequiredField", resourceCulture);
            }
        }
    }
}
